Repository fedimint/fedimint, pull requests merged in 2023-04, with the labels that each got.

#2093 fix: `PROTOC` not set in the dev shell
  flake.crane.nix
  flake.nix
Labels: api

#2175 One time join codes
  db/migrations/global-v0/000004.log
  db/migrations/global-v0/IDENTITY
  db/migrations/global-v0/LOG
  db/migrations/lightning-v0/000004.log
  db/migrations/lightning-v0/IDENTITY
  db/migrations/lightning-v0/LOG
  db/migrations/mint-v0/000004.log
  db/migrations/mint-v0/IDENTITY
  db/migrations/mint-v0/LOG
  db/migrations/wallet-v0/000004.log
  db/migrations/wallet-v0/IDENTITY
  db/migrations/wallet-v0/LOG
  fedimint-cli/src/lib.rs
  fedimint-client-legacy/src/lib.rs
  fedimint-core/src/api.rs
  fedimint-dbtool/src/dump.rs
  fedimint-server/src/config/api.rs
  fedimint-server/src/config/io.rs
  fedimint-server/src/config/mod.rs
  fedimint-server/src/consensus/mod.rs
  fedimint-server/src/db.rs
  fedimint-server/src/net/api.rs
  fedimintd/src/ui.rs
  gateway/ln-gateway/src/client.rs
  gateway/ln-gateway/tests/authentication_tests.rs
  integrationtests/tests/fixtures/mod.rs
  integrationtests/tests/tests.rs
  scripts/cli-test.sh
Labels: waiting-on-review

#2161 refactor: remove subscribe htlcs and complete_htlc
  Cargo.lock
  fedimint-testing/Cargo.toml
  fedimint-testing/src/ln/fixtures.rs
  gateway/ln-gateway/proto/gatewaylnrpc.proto
  gateway/ln-gateway/src/actor.rs
  gateway/ln-gateway/src/bin/cln_extension.rs
  gateway/ln-gateway/src/lib.rs
  gateway/ln-gateway/src/lnd.rs
  gateway/ln-gateway/src/lnrpc_client.rs
  integrationtests/Cargo.toml
  integrationtests/tests/fixtures/utils.rs
Labels: waiting-on-review

#2182 Consensus api refactor
  Cargo.lock
  fedimint-server/src/consensus/interconnect.rs
  fedimint-server/src/consensus/mod.rs
  fedimint-server/src/lib.rs
  fedimint-server/src/net/api.rs
  fedimint-testing/Cargo.toml
  fedimint-testing/src/btc/bitcoind.rs
  integrationtests/tests/fixtures/mod.rs
Labels: waiting-on-review

#2195 fix: remove sleep in gatewayd web server event loop
  gateway/ln-gateway/src/bin/gatewayd.rs
  gateway/ln-gateway/src/lib.rs
  gateway/ln-gateway/src/rpc/mod.rs
  gateway/ln-gateway/src/rpc/rpc_server.rs
  gateway/ln-gateway/tests/fixtures/mod.rs
Labels: waiting-on-review

#2310 Initialize UI
  docs/gateway.md
  flake.nix
  guardian-ui/.eslintignore
  guardian-ui/.eslintrc.json
  guardian-ui/.gitignore
  guardian-ui/.prettierrc
  guardian-ui/package.json
  guardian-ui/public/index.html
  guardian-ui/public/manifest.json
  guardian-ui/public/robots.txt
  guardian-ui/src/App.tsx
  guardian-ui/src/ColorModeSwitcher.tsx
  guardian-ui/src/index.tsx
  guardian-ui/src/react-app-env.d.ts
  guardian-ui/src/setupTests.ts
  guardian-ui/tsconfig.json
  guardian-ui/yarn.lock
Labels: ui, waiting-on-review
