Repository fedimint/fedimint, pull requests merged in 2023-11, with the labels that each got.

#3502 fix: Reduce client log levels
  fedimint-client/src/sm/executor.rs
  fedimint-core/src/db/mod.rs
Labels: backport releases/v0.1

#3515 feat: make federation info available before joining
  fedimint-cli/src/lib.rs
  fedimint-client/src/lib.rs
  fedimint-load-test-tool/src/common.rs
  fedimint-testing/src/federation.rs
  fedimint-wasm-tests/src/lib.rs
  gateway/ln-gateway/src/client.rs
Labels: client

#3455 feat: gateway checks network on connect federation
  fedimint-testing/src/gateway.rs
  gateway/cli/src/main.rs
  gateway/ln-gateway/src/db.rs
  gateway/ln-gateway/src/lib.rs
  gateway/ln-gateway/src/rpc/mod.rs
  gateway/ln-gateway/tests/integration_tests.rs
Labels: backport releases/v0.1

#3516 Review and fix retry behavior of all state machines
  fedimint-core/src/api.rs
  modules/fedimint-dummy-client/src/states.rs
  modules/fedimint-dummy-tests/tests/tests.rs
  modules/fedimint-ln-client/Cargo.toml
  modules/fedimint-ln-client/src/pay.rs
  modules/fedimint-ln-client/src/receive.rs
  modules/fedimint-ln-common/src/api.rs
  modules/fedimint-wallet-client/src/withdraw.rs
Labels: bug, client, backport releases/v0.1

#3524 fix: make sure we consider a transaction rejected only if it is actually invalid
  fedimint-client/src/lib.rs
  fedimint-client/src/transaction/sm.rs
  fedimint-core/src/api.rs
  fedimint-server/src/net/api.rs
  modules/fedimint-dummy-tests/tests/tests.rs
Labels: backport releases/v0.1

#3597 chore: build binaries on release branch
  .github/workflows/ci-nix.yml
Labels: backport releases/v0.1

#3631 chore: add timing logs to module audits
  fedimint-core/src/timing.rs
  fedimint-server/src/consensus/server.rs
Labels: backport releases/v0.1

#3688 fix(client): only list operation ids with associated operations as active
  fedimint-client/src/lib.rs
  fedimint-client/src/sm/executor.rs
Labels: client

#3719 chore: move to self-published version of ldk-node
  Cargo.lock
  fedimint-testing/Cargo.toml
Labels: backport releases/v0.2

#3721 chore: ensure prefix `fedimint` on all published crates
  Cargo.lock
  crypto/derive-secret/Cargo.toml
  crypto/hkdf/Cargo.toml
  crypto/tbs/Cargo.toml
  devimint/Cargo.toml
  fedimint-core/Cargo.toml
  fedimint-dbtool/Cargo.toml
  fedimint-load-test-tool/Cargo.toml
  fedimint-server/Cargo.toml
  fedimint-testing/Cargo.toml
  fedimint-wasm-tests/Cargo.toml
  fedimintd/Cargo.toml
  gateway/cli/Cargo.toml
  gateway/ln-gateway/Cargo.toml
  misc/git-hooks/pre-commit
  modules/fedimint-ln-tests/Cargo.toml
  modules/fedimint-mint-client/Cargo.toml
  modules/fedimint-mint-common/Cargo.toml
  modules/fedimint-mint-server/Cargo.toml
  modules/fedimint-mint-tests/Cargo.toml
  modules/fedimint-wallet-tests/Cargo.toml
  nix/check-forbidden-deps.sh
  nix/flakebox.nix
  recoverytool/Cargo.toml
Labels: backport releases/v0.2

#3735 feat: read git hash from .cargo_vcs_info.json if compiling release
  Cargo.lock
  fedimint-build/Cargo.toml
  fedimint-build/src/lib.rs
Labels: backport releases/v0.2

#3734 fix: `MintOperationMetaVariant` uses singular name
  modules/fedimint-mint-client/src/lib.rs
Labels: backport releases/v0.2

#3742 fix(cln-extension): avoid holding the sender lock during HTLC processing
  gateway/ln-gateway/src/bin/cln_extension.rs
  gateway/ln-gateway/src/lib.rs
Labels: backport releases/v0.2

#3746 fix: use 33 byte tweaks in recovery tool parser
  Cargo.lock
  recoverytool/Cargo.toml
  recoverytool/src/main.rs
Labels: backport releases/v0.2

#3756 chore: ignore uncommitted dbtx writes for endpoint audits
  fedimint-server/src/net/api.rs
Labels: backport releases/v0.2

#3740 fedimint-client secret derivation path in fedimint-CLI
  Cargo.lock
  crypto/derive-secret/src/lib.rs
  docs/secret_derivation.md
  fedimint-cli/Cargo.toml
  fedimint-cli/src/client.rs
  fedimint-cli/src/lib.rs
  fedimint-client/src/lib.rs
  fedimint-client/src/secret.rs
Labels: backport releases/v0.2

#3758 simplification: always propose block height and feerate votes
  fedimint-server/src/consensus/server.rs
  modules/fedimint-ln-server/src/lib.rs
  modules/fedimint-wallet-server/src/lib.rs
Labels: backport releases/v0.2

#3775 fix: avoid warnings on recovery from mid session crash
  fedimint-core/src/db/mod.rs
  fedimint-server/src/consensus/server.rs
Labels: backport releases/v0.2

#3776 chore: add repo link to `Cargo.toml` of published crates
  crypto/aead/Cargo.toml
  crypto/derive-secret/Cargo.toml
  crypto/hkdf/Cargo.toml
  crypto/tbs/Cargo.toml
  fedimint-bip39/Cargo.toml
  fedimint-bitcoind/Cargo.toml
  fedimint-build/Cargo.toml
  fedimint-cli/Cargo.toml
  fedimint-client/Cargo.toml
  fedimint-core/Cargo.toml
  fedimint-dbtool/Cargo.toml
  fedimint-derive/Cargo.toml
  fedimint-logging/Cargo.toml
  fedimint-metrics/Cargo.toml
  fedimint-rocksdb/Cargo.toml
  fedimint-server/Cargo.toml
  fedimint-testing/Cargo.toml
  fedimintd/Cargo.toml
  gateway/cli/Cargo.toml
  gateway/ln-gateway/Cargo.toml
  modules/fedimint-dummy-client/Cargo.toml
  modules/fedimint-dummy-common/Cargo.toml
  modules/fedimint-dummy-server/Cargo.toml
  modules/fedimint-ln-client/Cargo.toml
  modules/fedimint-ln-common/Cargo.toml
  modules/fedimint-ln-server/Cargo.toml
  modules/fedimint-mint-client/Cargo.toml
  modules/fedimint-mint-common/Cargo.toml
  modules/fedimint-mint-server/Cargo.toml
  modules/fedimint-wallet-client/Cargo.toml
  modules/fedimint-wallet-common/Cargo.toml
  modules/fedimint-wallet-server/Cargo.toml
  recoverytool/Cargo.toml
  utils/portalloc/Cargo.toml
Labels: backport releases/v0.2

#3749 feat: can pass --auth flag to `fedimint-cli dev api`
  fedimint-cli/src/lib.rs
Labels: backport releases/v0.2

#3755 fix 'withdraw all' feature
  fedimint-cli/src/client.rs
  fedimint-core/src/lib.rs
  gateway/ln-gateway/src/lib.rs
Labels: backport releases/v0.2
