Repository fedimint/fedimint, pull requests merged in 2024-04, with the labels that each got.

#4783 feat: add Waiter helper in fedimint-core
  fedimint-core/src/task.rs
  fedimint-core/src/task/waiter.rs
Labels: backport releases/v0.3

#4766 feat: update ln gateway cache in background
  modules/fedimint-ln-client/src/lib.rs
Labels: backport releases/v0.3

#4768 feat: meta caching
  Cargo.lock
  fedimint-client/Cargo.toml
  fedimint-client/src/db.rs
  fedimint-client/src/lib.rs
  fedimint-client/src/meta.rs
Labels: backport releases/v0.3

#4787 feat: subscriptions for meta fields
  fedimint-client/src/meta.rs
Labels: backport releases/v0.3

#4799 fix: use random gateway on cli when gateway not specified
  devimint/src/tests.rs
  devimint/src/version_constants.rs
  fedimint-cli/src/client.rs
Labels: backport releases/v0.3

#4898 chore(consensus): log items failing max size validation
  fedimint-server/src/atomic_broadcast/data_provider.rs
Labels: backport releases/v0.2, backport releases/v0.3

#4956 refactor: GlobalApi should make non-admin calls to all peers
  devimint/src/federation.rs
  fedimint-api-client/src/api.rs
  fedimint-cli/src/lib.rs
  fedimint-client/src/lib.rs
  fedimint-server/src/config/api.rs
Labels: needs further review

#4972 feat(devimint): start from a previous state (skip setup)
  .gitignore
  devimint/src/cli.rs
  devimint/src/devfed.rs
  devimint/src/external.rs
  devimint/src/federation.rs
  devimint/src/lib.rs
  devimint/src/util.rs
  devimint/src/vars.rs
  fedimint-bitcoind/src/bitcoincore.rs
  fedimint-bitcoind/src/lib.rs
  fedimint-core/src/envs.rs
  fedimint-server/src/consensus/server.rs
  fedimint-testing/src/fixtures.rs
  fedimintd/src/fedimintd.rs
  modules/fedimint-wallet-client/src/lib.rs
Labels: needs further review

#4970 chore: fix, improve, speedup recovery
  fedimint-api-client/src/api.rs
  fedimint-cli/src/lib.rs
  fedimint-client/src/lib.rs
  fedimint-client/src/module/init/recovery.rs
  modules/fedimint-mint-client/src/backup/recovery.rs
Labels: backport releases/v0.3

#5011 chore: make fedimintd and devimint shutdown stuff fast
  devimint/src/util.rs
  fedimint-server/src/lib.rs
  fedimint-testing/src/federation.rs
  fedimintd/src/fedimintd.rs
Labels: needs further review

#5003 chore: don't assume that a inputs / outputs know their amounts, track amounts in ClientInput / ClientOutput instead
  fedimint-client/src/lib.rs
  fedimint-client/src/module/mod.rs
  fedimint-client/src/transaction/builder.rs
  gateway/ln-gateway/src/gateway_module_v2/mod.rs
  gateway/ln-gateway/src/gateway_module_v2/receive_sm.rs
  gateway/ln-gateway/src/gateway_module_v2/send_sm.rs
  gateway/ln-gateway/src/state_machine/mod.rs
  gateway/ln-gateway/src/state_machine/pay.rs
  gateway/ln-gateway/tests/integration_tests.rs
  modules/fedimint-dummy-client/src/lib.rs
  modules/fedimint-dummy-tests/tests/tests.rs
  modules/fedimint-empty-client/src/lib.rs
  modules/fedimint-ln-client/src/incoming.rs
  modules/fedimint-ln-client/src/lib.rs
  modules/fedimint-ln-client/src/pay.rs
  modules/fedimint-ln-client/src/receive.rs
  modules/fedimint-lnv2-client/src/lib.rs
  modules/fedimint-lnv2-client/src/receive_sm.rs
  modules/fedimint-lnv2-client/src/send_sm.rs
  modules/fedimint-lnv2-common/src/lib.rs
  modules/fedimint-lnv2-server/src/lib.rs
  modules/fedimint-meta-client/src/lib.rs
  modules/fedimint-mint-client/src/input.rs
  modules/fedimint-mint-client/src/lib.rs
  modules/fedimint-mint-client/src/oob.rs
  modules/fedimint-wallet-client/src/deposit.rs
  modules/fedimint-wallet-client/src/lib.rs
Labels: needs further review

#5040 fix: inefficient way to look for file
  fedimint-testing/src/db.rs
Labels: needs further review

#5142 fix(devimint): reset chan policy on retry
  devimint/src/external.rs
Labels: needs further review

#5149 chore(devimint): fix most of flakiness in setting up LN gateways
  devimint/src/devfed.rs
  devimint/src/external.rs
  devimint/src/gatewayd.rs
  devimint/src/tests.rs
  fedimint-api-client/src/api.rs
  fedimint-core/src/task/jit.rs
  gateway/ln-gateway/src/lib.rs
  scripts/tests/test-ci-all.sh
Labels: needs further review

#4776 Gateway liquidity api can list active channels
  devimint/src/external.rs
  devimint/src/gatewayd.rs
  docs/gateway.md
  fedimint-testing/src/ln/mock.rs
  fedimint-testing/src/ln/real.rs
  gateway/cli/src/main.rs
  gateway/ln-gateway/proto/gateway_lnrpc.proto
  gateway/ln-gateway/src/bin/cln_extension.rs
  gateway/ln-gateway/src/lib.rs
  gateway/ln-gateway/src/lightning/cln.rs
  gateway/ln-gateway/src/lightning/lnd.rs
  gateway/ln-gateway/src/lightning/mod.rs
  gateway/ln-gateway/src/rpc/rpc_client.rs
  gateway/ln-gateway/src/rpc/rpc_server.rs
Labels: needs further review

#4477 refactor: create_final_inputs_and_outputs
  fedimint-client/src/lib.rs
  fedimint-client/src/module/mod.rs
  fedimint-client/src/transaction/builder.rs
  fedimint-core/src/lib.rs
  fedimint-load-test-tool/src/common.rs
  modules/fedimint-dummy-client/src/lib.rs
  modules/fedimint-mint-client/src/lib.rs
Labels: needs further review
