Repository fedimint/fedimint, pull requests merged in 2024-05, with the labels that each got.

#5128 refactor(mint-client): `SpendableNoteUndecoded` faster note handling
  Cargo.lock
  Cargo.toml
  fedimint-core/Cargo.toml
  modules/fedimint-mint-client/Cargo.toml
  modules/fedimint-mint-client/src/backup.rs
  modules/fedimint-mint-client/src/backup/recovery.rs
  modules/fedimint-mint-client/src/client_db.rs
  modules/fedimint-mint-client/src/lib.rs
  modules/fedimint-mint-client/src/output.rs
  modules/fedimint-mint-tests/tests/tests.rs
Labels: needs further review

#5179 chore: Mock RPCs between Client -> Gateway
  fedimint-cli/src/lib.rs
  fedimint-dbtool/src/main.rs
  fedimint-load-test-tool/src/common.rs
  fedimint-testing/src/gateway.rs
  fedimint-wasm-tests/src/lib.rs
  gateway/ln-gateway/src/state_machine/mod.rs
  gateway/ln-gateway/tests/integration_tests.rs
  modules/fedimint-ln-client/src/lib.rs
  modules/fedimint-ln-client/src/pay.rs
  modules/fedimint-ln-client/src/receive.rs
  modules/fedimint-ln-common/src/lib.rs
  modules/fedimint-ln-tests/tests/tests.rs
  modules/fedimint-lnv2-tests/tests/tests.rs
Labels: needs further review

#5189 fix(server): panic when there are no peers
  fedimint-server/src/net/peers.rs
  fedimint-server/src/net/peers_reliable.rs
Labels: backport releases/v0.3, needs further review

#5184 fix(recoverytest): wait for next session before scanning session outcomes for pegins
  devimint/src/federation.rs
  devimint/src/tests.rs
Labels: testing, wallet

#5188 chore(nix-module): improvements
  nix/modules/fedimintd.nix
Labels: backport releases/v0.3

#5206 fixes and debugging improvements
  fedimint-client/src/sm/executor.rs
  fedimint-core/src/transaction.rs
  modules/fedimint-mint-client/src/input.rs
Labels: needs further review

#5201 chore: simplify FederationId and FederationIdPrefix string decoding
  fedimint-core/src/config.rs
Labels: needs further review

#5234 fix: use async mutex
  fedimint-server/src/config/api.rs
  fedimint-server/src/lib.rs
Labels: needs further review

#5224 cleanup: simplify verification hashes
  fedimint-server/src/config/api.rs
  fedimint-server/src/lib.rs
  fedimint-server/src/net/api.rs
Labels: needs further review

#5237 fix: typed error for pay_bolt11_invoice
  modules/fedimint-ln-client/src/lib.rs
Labels: backport releases/v0.3

#5236 fix: typed error for reissue external notes
  modules/fedimint-mint-client/src/lib.rs
Labels: backport releases/v0.3

#5247 Small improvements to Fedimint Server
  Cargo.lock
  fedimint-server/Cargo.toml
  fedimint-server/src/atomic_broadcast/keychain.rs
  fedimint-server/src/atomic_broadcast/spawner.rs
  fedimint-server/src/config/mod.rs
  fedimint-server/src/consensus/server.rs
  fedimint-server/src/db.rs
  fedimint-server/src/net/api.rs
  fedimint-server/src/net/peers.rs
Labels: needs further review

#5264 Refactor server
  fedimint-server/src/consensus/engine.rs
  fedimint-server/src/consensus/mod.rs
  fedimint-server/src/consensus/transaction.rs
  fedimint-server/src/lib.rs
  fedimint-server/src/net/api.rs
  fedimint-testing/src/federation.rs
Labels: needs further review

#5294 fix(fedimintd): doesn't print version on start
  fedimintd/src/fedimintd.rs
Labels: backport releases/v0.3

#4024 refactor: remove refundable state
  db/migrations/lightning-client-v0/000004.log
  db/migrations/lightning-client-v0/IDENTITY
  db/migrations/lightning-client-v0/LOG
  db/migrations/lightning-client-v0/OPTIONS-000007
  fedimint-load-test-tool/src/common.rs
  gateway/ln-gateway/tests/integration_tests.rs
  modules/fedimint-ln-client/src/db.rs
  modules/fedimint-ln-client/src/lib.rs
  modules/fedimint-ln-client/src/pay.rs
  modules/fedimint-ln-tests/tests/tests.rs
Labels: needs further review

#5307 fix: recognize change outputs for bitcoind backends without txindex
  devimint/src/cfg/bitcoin.conf
  devimint/src/external.rs
  fedimint-bitcoind/src/bitcoincore.rs
  fedimint-bitcoind/src/electrum.rs
  fedimint-bitcoind/src/esplora.rs
  fedimint-bitcoind/src/lib.rs
  fedimint-testing/src/btc/mock.rs
  fedimint-testing/src/btc/mod.rs
  fedimint-testing/src/btc/real.rs
  modules/fedimint-wallet-server/src/lib.rs
  modules/fedimint-wallet-tests/tests/tests.rs
Labels: backport releases/v0.3, needs further review

#5311 chore: port in url handling improvements
  fedimint-core/src/net/mod.rs
  fedimint-core/src/util/mod.rs
  fedimint-server/src/net/peers.rs
Labels: backport releases/v0.3

#5340 chore: add more logging when state machines are being added
  fedimint-client/src/sm/executor.rs
Labels: backport releases/v0.3

#5042 feat: minimal mainnet fedimintd docker setup
  docker/0.3.0/fedimintd-mainnet-tls/.env
  docker/0.3.0/fedimintd-mainnet-tls/docker-compose.yaml
  docker/0.3.0/fedimintd-mainnet-tls/meta.json
Labels: deployment
