Repository fedimint/fedimint, pull requests merged in 2024-11, with the labels that each got.

#6253 fix: remove leading and trailing newlines from password
  fedimint-server/src/config/api.rs
  fedimint-server/src/lib.rs
Labels: backport releases/v0.4

#6285 refactor(client): handle multiple outputs with a single state machine
  Cargo.lock
  Cargo.toml
  fedimint-server/Cargo.toml
  modules/fedimint-mint-client/Cargo.toml
  modules/fedimint-mint-client/src/backup.rs
  modules/fedimint-mint-client/src/backup/recovery.rs
  modules/fedimint-mint-client/src/client_db.rs
  modules/fedimint-mint-client/src/lib.rs
  modules/fedimint-mint-client/src/output.rs
Labels: needs further review

#6309 fix: LNv1 add min_cltv_delta to timelock constant
  devimint/src/external.rs
  modules/fedimint-ln-client/src/lib.rs
Labels: backport releases/v0.4

#6339 fix(net): flood of log messages on disconnected peer
  fedimint-server/src/net/peers.rs
Labels: backport releases/v0.4

#6359 fix: mint client state machine migration
  modules/fedimint-mint-client/src/client_db.rs
  modules/fedimint-mint-client/src/input.rs
  modules/fedimint-mint-client/src/oob.rs
  modules/fedimint-mint-client/src/output.rs
Labels: backport releases/v0.5

#6357 chore: switch to using jemalloc on all major binaries.
  Cargo.lock
  Cargo.toml
  fedimint-cli/Cargo.toml
  fedimint-cli/src/main.rs
  fedimintd/Cargo.toml
  fedimintd/src/bin/main.rs
  gateway/ln-gateway/Cargo.toml
  gateway/ln-gateway/src/bin/gatewayd.rs
Labels: backport releases/v0.5

#6386 chore: use fibonacci backoff for waiting for finality delay confs
  fedimint-core/src/util/backoff_util.rs
  modules/fedimint-wallet-server/src/lib.rs
Labels: backport releases/v0.5

#6418 chore(devimint): ability to force-disable lnv2 module
  devimint/src/devfed.rs
  devimint/src/federation/config.rs
  devimint/src/gatewayd.rs
  devimint/src/vars.rs
  fedimint-core/src/envs.rs
Labels: backport releases/v0.5

#6382 Fix wallet tx size limit
  db/migrations/wallet-server-v0/000004.log
  db/migrations/wallet-server-v0/IDENTITY
  db/migrations/wallet-server-v0/LOG
  db/migrations/wallet-server-v0/OPTIONS-000007
  fedimint-bitcoind/src/bitcoincore.rs
  fedimint-bitcoind/src/electrum.rs
  fedimint-bitcoind/src/esplora.rs
  fedimint-bitcoind/src/lib.rs
  fedimint-core/src/encoding/btc.rs
  fedimint-core/src/module/version.rs
  fedimint-recoverytool/src/main.rs
  fedimint-testing/src/btc/mock.rs
  modules/fedimint-wallet-client/src/api.rs
  modules/fedimint-wallet-client/src/backup.rs
  modules/fedimint-wallet-client/src/deposit.rs
  modules/fedimint-wallet-client/src/lib.rs
  modules/fedimint-wallet-client/src/pegin_monitor.rs
  modules/fedimint-wallet-common/src/endpoint_constants.rs
  modules/fedimint-wallet-common/src/lib.rs
  modules/fedimint-wallet-server/src/db.rs
  modules/fedimint-wallet-server/src/lib.rs
  modules/fedimint-wallet-tests/tests/tests.rs
Labels: needs further review

#6430 fix: deactivate cross compile dev shell for aarch64-linux
  flake.nix
Labels: backport releases/v0.5

#6458 chore(recovery): save reused note indices
  modules/fedimint-mint-client/src/backup/recovery.rs
  modules/fedimint-mint-client/src/client_db.rs
  modules/fedimint-mint-client/src/lib.rs
  modules/fedimint-mint-client/src/output.rs
  modules/fedimint-mint-tests/tests/tests.rs
Labels: backport releases/v0.5
