Repository fedimint/fedimint, pull requests merged in 2025-04, with the labels that each got.

#7138 chore(build): give up on iroh being optional build feature
  .config/flakebox/id
  Cargo.lock
  Cargo.toml
  devimint/Cargo.toml
  fedimint-api-client/Cargo.toml
  fedimint-api-client/src/api/mod.rs
  fedimint-cli/Cargo.toml
  fedimint-client-module/Cargo.toml
  fedimint-client-wasm/Cargo.toml
  fedimint-client/Cargo.toml
  fedimint-server/Cargo.toml
  fedimint-wasm-tests/Cargo.toml
  fedimint-wasm-tests/src/lib.rs
  fedimint-workspace/Cargo.toml
  fedimintd/Cargo.toml
  flake.nix
  justfile
  nix/overlays/wasm-bindgen.nix
  scripts/tests/wasm-test.sh
Labels: backport releases/v0.7

#7140 Wallet UI Improvements
  fedimint-server-ui/src/invite_code.rs
  fedimint-server-ui/src/lnv2.rs
  fedimint-server-ui/src/wallet.rs
  modules/fedimint-wallet-server/src/lib.rs
Labels: backport releases/v0.7

#7147 fix: set default lnv2 fee to 0.01%
  fedimintd/src/fedimintd.rs
  modules/fedimint-lnv2-tests/bin/tests.rs
Labels: backport releases/v0.7

#7151 chore: print more error information for `PeerError`
  fedimint-api-client/src/api/error.rs
Labels: backport releases/v0.6, backport releases/v0.7

#7155 fix: add async feature to lnurlp
  lnurlp/Cargo.toml
Labels: backport releases/v0.7

#7162 fix: add missing metadata to fedimint-recurringd Cargo.toml
  fedimint-recurringd/Cargo.toml
  fedimint-recurringd/README.md
  fedimint-recurringd/src/db.rs
  fedimint-recurringd/src/lib.rs
  fedimint-recurringd/src/main.rs
Labels: backport releases/v0.7

#7179 chore: build and publish fedimint-recurringd container
  .github/workflows/ci-nix.yml
  nix/flakebox.nix
Labels: backport releases/v0.7

#7189 fix: add zlib to resolve linker errors
  nix/flakebox.nix
Labels: backport releases/v0.7

#7255 chore(consensus): improve debugging of rejected citems
  fedimint-server/src/consensus/engine.rs
Labels: backport releases/v0.6, backport releases/v0.7

#7249 chore(ci): specify architecture for self-hosted runners
  .github/workflows/ci-backwards-compatibility.yml
  .github/workflows/ci-fuzz.yml
  .github/workflows/ci-nix.yml
  .github/workflows/daily.yml
  .github/workflows/docs.yml
  .github/workflows/hourly-run.yml
  .github/workflows/upgrade-tests.yml
Labels: backport releases/v0.5, backport releases/v0.6, backport releases/v0.7

#7287 feat: add reset_peer_setup_codes to api-client
  fedimint-api-client/src/api/global_api/with_cache.rs
  fedimint-api-client/src/api/mod.rs
Labels: backport releases/v0.7

#7338 chore: make deposits on test networks faster
  fedimintd/src/lib.rs
Labels: wallet

#7329 fix: fix possible double counting of previous response by the same peer
  fedimint-api-client/src/query.rs
Labels: backport releases/v0.5, backport releases/v0.6, backport releases/v0.7
