Repository fedimint/fedimint, pull requests merged in 2025-05, with the labels that each got.

#7408 feat: implement get_invite_code on fedimint-api-client
  fedimint-api-client/src/api/global_api/with_cache.rs
  fedimint-api-client/src/api/mod.rs
Labels: backport releases/v0.7

#7420 chore: disable jemalloc on android
  fedimint-cli/Cargo.toml
  fedimint-cli/src/main.rs
  fedimint-rocksdb/Cargo.toml
  fedimintd/Cargo.toml
  fedimintd/src/bin/main.rs
  gateway/fedimint-gateway-server/Cargo.toml
  gateway/fedimint-gateway-server/src/bin/gatewayd.rs
Labels: backport releases/v0.7

#7449 fix: unnecessary `Result` in `list_peg_in_tweak_idxes`
  modules/fedimint-wallet-client/src/lib.rs
Labels: backport releases/v0.6, backport releases/v0.7

#7445 fix(setup): make `set_local_parameters` idempotent
  fedimint-server/src/config/setup.rs
Labels: backport releases/v0.7

#7457 fix(recurringd): actually check admin auth
  Cargo.lock
  Cargo.toml
  fedimint-recurringd-tests/Cargo.toml
  fedimint-recurringd-tests/src/bin/fedimint-recurringd-tests.rs
  fedimint-recurringd/Cargo.toml
  fedimint-recurringd/src/main.rs
Labels: backport releases/v0.7

#7458 chore(docker): actually enable firewall
  docker/deploy-fedimintd/deploy.sh
Labels: backport releases/v0.6, backport releases/v0.7

#7438 feat: add get_setup_code to DKG
  fedimint-api-client/src/api/global_api/with_cache.rs
  fedimint-api-client/src/api/mod.rs
  fedimint-core/src/endpoint_constants.rs
  fedimint-server/src/config/setup.rs
Labels: backport releases/v0.7

#7478 fix(client): fetch api announcements on join
  devimint/src/tests.rs
  fedimint-api-client/src/lib.rs
  fedimint-cli/src/lib.rs
  fedimint-client-wasm/src/lib.rs
  fedimint-client/src/api_announcements.rs
  fedimint-client/src/client.rs
  fedimint-client/src/client/builder.rs
  fedimint-client/src/lib.rs
  fedimint-load-test-tool/src/common.rs
  fedimint-recurringd/src/lib.rs
  fedimint-testing/src/federation.rs
  fedimint-wasm-tests/src/lib.rs
  gateway/fedimint-gateway-server/src/client.rs
Labels: needs further review
